var s_iScaleFactor=1,s_iOffsetX,s_iOffsetY;
(function(a){(jQuery.browser=jQuery.browser||{}).mobile=/android|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(ad|hone|od)|iris|kindle|lge |maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|symbian|tablet|treo|up\.(browser|link)|vodafone|wap|webos|windows (ce|phone)|xda|xiino/i.test(a)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|e\-|e\/|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(di|rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|xda(\-|2|g)|yas\-|your|zeto|zte\-/i.test(a.substr(0,4))})(navigator.userAgent||
navigator.vendor||window.opera);$(window).resize(function(){sizeHandler()});function trace(a){console.log(a)}
function getSize(a){var e=a.toLowerCase(),b=window.document,c=b.documentElement;if(void 0===window["inner"+a])a=c["client"+a];else if(window["inner"+a]!=c["client"+a]){var f=b.createElement("body");f.id="vpw-test-b";f.style.cssText="overflow:scroll";var d=b.createElement("div");d.id="vpw-test-d";d.style.cssText="position:absolute;top:-1000px";d.innerHTML="<style>@media("+e+":"+c["client"+a]+"px){body#vpw-test-b div#vpw-test-d{"+e+":7px!important}}</style>";f.appendChild(d);c.insertBefore(f,b.head);
a=7==d["offset"+a]?c["client"+a]:window["inner"+a];c.removeChild(f)}else a=window["inner"+a];return a}window.addEventListener("orientationchange",onOrientationChange);function onOrientationChange(){window.matchMedia("(orientation: portrait)").matches&&sizeHandler();window.matchMedia("(orientation: landscape)").matches&&sizeHandler()}
function isIOS(){for(var a="iPad Simulator;iPhone Simulator;iPod Simulator;iPad;iPhone;iPod".split(";");a.length;)if(navigator.platform===a.pop())return s_bIsIphone=!0;return s_bIsIphone=!1}function getIOSWindowHeight(){return document.documentElement.clientWidth/window.innerWidth*window.innerHeight}function getHeightOfIOSToolbars(){var a=(0===window.orientation?screen.height:screen.width)-getIOSWindowHeight();return 1<a?a:0}
function sizeHandler(){window.scrollTo(0,1);if($("#canvas")){var a=navigator.userAgent.match(/(iPad|iPhone|iPod)/g)?getIOSWindowHeight():getSize("Height");var e=getSize("Width");_checkOrientation(e,a);var b=Math.min(a/CANVAS_HEIGHT,e/CANVAS_WIDTH),c=CANVAS_WIDTH*b;b*=CANVAS_HEIGHT;if(b<a){var f=a-b;b+=f;c+=CANVAS_WIDTH/CANVAS_HEIGHT*f}else c<e&&(f=e-c,c+=f,b+=CANVAS_HEIGHT/CANVAS_WIDTH*f);f=a/2-b/2;var d=e/2-c/2,h=CANVAS_WIDTH/c;if(d*h<-EDGEBOARD_X||f*h<-EDGEBOARD_Y)b=Math.min(a/(CANVAS_HEIGHT-2*
EDGEBOARD_Y),e/(CANVAS_WIDTH-2*EDGEBOARD_X)),c=CANVAS_WIDTH*b,b*=CANVAS_HEIGHT,f=(a-b)/2,d=(e-c)/2,h=CANVAS_WIDTH/c;s_iOffsetX=-1*d*h;s_iOffsetY=-1*f*h;0<=f&&(s_iOffsetY=0);0<=d&&(s_iOffsetX=0);null!==s_oInterface&&s_oInterface.refreshButtonPos(s_iOffsetX,s_iOffsetY);null!==s_oMenu&&s_oMenu.refreshButtonPos(s_iOffsetX,s_iOffsetY);$("#canvas").css("width",c+"px");$("#canvas").css("height",b+"px");0>f?$("#canvas").css("top",f+"px"):$("#canvas").css("top","0px");$("#canvas").css("left",d+"px")}}
function _checkOrientation(a,e){s_bMobile&&ENABLE_CHECK_ORIENTATION&&(a>e?"landscape"===$(".orientation-msg-container").attr("data-orientation")?($(".orientation-msg-container").css("display","none"),s_oMain.startUpdate()):($(".orientation-msg-container").css("display","block"),s_oMain.stopUpdate()):"portrait"===$(".orientation-msg-container").attr("data-orientation")?($(".orientation-msg-container").css("display","none"),s_oMain.startUpdate()):($(".orientation-msg-container").css("display","block"),
s_oMain.stopUpdate()))}function inIframe(){try{return window.self!==window.top}catch(a){return!0}}function createBitmap(a,e,b){var c=new createjs.Bitmap(a),f=new createjs.Shape;e&&b?f.graphics.beginFill("#fff").drawRect(0,0,e,b):f.graphics.beginFill("#ff0").drawRect(0,0,a.width,a.height);c.hitArea=f;return c}function createSprite(a,e,b,c,f,d){a=null!==e?new createjs.Sprite(a,e):new createjs.Sprite(a);e=new createjs.Shape;e.graphics.beginFill("#000000").drawRect(-b,-c,f,d);a.hitArea=e;return a}
function pad(a,e,b){a+="";return a.length>=e?a:Array(e-a.length+1).join(b||"0")+a}function randomFloatBetween(a,e,b){"undefined"===typeof b&&(b=2);return parseFloat(Math.min(a+Math.random()*(e-a),e).toFixed(b))}function rotateVector2D(a,e){var b=e.getX()*Math.cos(a)+e.getY()*Math.sin(a),c=e.getX()*-Math.sin(a)+e.getY()*Math.cos(a);e.set(b,c)}function tweenVectorsOnX(a,e,b){return a+b*(e-a)}
function shuffle(a){for(var e=a.length,b,c;0!==e;)c=Math.floor(Math.random()*e),--e,b=a[e],a[e]=a[c],a[c]=b;return a}function bubbleSort(a){do{var e=!1;for(var b=0;b<a.length-1;b++)a[b]>a[b+1]&&(e=a[b],a[b]=a[b+1],a[b+1]=e,e=!0)}while(e)}function compare(a,e){return a.index>e.index?-1:a.index<e.index?1:0}function easeLinear(a,e,b,c){return b*a/c+e}function easeInQuad(a,e,b,c){return b*(a/=c)*a+e}function easeInSine(a,e,b,c){return-b*Math.cos(a/c*(Math.PI/2))+b+e}
function easeInCubic(a,e,b,c){return b*(a/=c)*a*a+e}function getTrajectoryPoint(a,e){var b=new createjs.Point,c=(1-a)*(1-a),f=a*a;b.x=c*e.start.x+2*(1-a)*a*e.traj.x+f*e.end.x;b.y=c*e.start.y+2*(1-a)*a*e.traj.y+f*e.end.y;return b}function formatTime(a){a/=1E3;var e=Math.floor(a/60);a=parseFloat(a-60*e).toFixed(1);var b="";b=10>e?b+("0"+e+":"):b+(e+":");return 10>a?b+("0"+a):b+a}function degreesToRadians(a){return a*Math.PI/180}
function checkRectCollision(a,e){var b=getBounds(a,.9);var c=getBounds(e,.98);return calculateIntersection(b,c)}function calculateIntersection(a,e){var b,c,f,d;var h=a.x+(b=a.width/2);var l=a.y+(c=a.height/2);var g=e.x+(f=e.width/2);var m=e.y+(d=e.height/2);h=Math.abs(h-g)-(b+f);l=Math.abs(l-m)-(c+d);return 0>h&&0>l?(h=Math.min(Math.min(a.width,e.width),-h),l=Math.min(Math.min(a.height,e.height),-l),{x:Math.max(a.x,e.x),y:Math.max(a.y,e.y),width:h,height:l,rect1:a,rect2:e}):null}
function getBounds(a,e){var b={x:Infinity,y:Infinity,width:0,height:0};if(a instanceof createjs.Container){b.x2=-Infinity;b.y2=-Infinity;var c=a.children,f=c.length,d;for(d=0;d<f;d++){var h=getBounds(c[d],1);h.x<b.x&&(b.x=h.x);h.y<b.y&&(b.y=h.y);h.x+h.width>b.x2&&(b.x2=h.x+h.width);h.y+h.height>b.y2&&(b.y2=h.y+h.height)}Infinity==b.x&&(b.x=0);Infinity==b.y&&(b.y=0);Infinity==b.x2&&(b.x2=0);Infinity==b.y2&&(b.y2=0);b.width=b.x2-b.x;b.height=b.y2-b.y;delete b.x2;delete b.y2}else{if(a instanceof createjs.Bitmap){f=
a.sourceRect||a.image;d=f.width*e;var l=f.height*e}else if(a instanceof createjs.Sprite)if(a.spriteSheet._frames&&a.spriteSheet._frames[a.currentFrame]&&a.spriteSheet._frames[a.currentFrame].image){f=a.spriteSheet.getFrame(a.currentFrame);d=f.rect.width;l=f.rect.height;c=f.regX;var g=f.regY}else b.x=a.x||0,b.y=a.y||0;else b.x=a.x||0,b.y=a.y||0;c=c||0;d=d||0;g=g||0;l=l||0;b.regX=c;b.regY=g;f=a.localToGlobal(0-c,0-g);h=a.localToGlobal(d-c,l-g);d=a.localToGlobal(d-c,0-g);c=a.localToGlobal(0-c,l-g);b.x=
Math.min(Math.min(Math.min(f.x,h.x),d.x),c.x);b.y=Math.min(Math.min(Math.min(f.y,h.y),d.y),c.y);b.width=Math.max(Math.max(Math.max(f.x,h.x),d.x),c.x)-b.x;b.height=Math.max(Math.max(Math.max(f.y,h.y),d.y),c.y)-b.y}return b}function NoClickDelay(a){this.element=a;window.Touch&&this.element.addEventListener("touchstart",this,!1)}function shuffle(a){for(var e=a.length,b,c;0<e;)c=Math.floor(Math.random()*e),e--,b=a[e],a[e]=a[c],a[c]=b;return a}
NoClickDelay.prototype={handleEvent:function(a){switch(a.type){case "touchstart":this.onTouchStart(a);break;case "touchmove":this.onTouchMove(a);break;case "touchend":this.onTouchEnd(a)}},onTouchStart:function(a){a.preventDefault();this.moved=!1;this.element.addEventListener("touchmove",this,!1);this.element.addEventListener("touchend",this,!1)},onTouchMove:function(a){this.moved=!0},onTouchEnd:function(a){this.element.removeEventListener("touchmove",this,!1);this.element.removeEventListener("touchend",
this,!1);if(!this.moved){a=document.elementFromPoint(a.changedTouches[0].clientX,a.changedTouches[0].clientY);3==a.nodeType&&(a=a.parentNode);var e=document.createEvent("MouseEvents");e.initEvent("click",!0,!0);a.dispatchEvent(e)}}};
(function(){function a(a){var b={focus:"visible",focusin:"visible",pageshow:"visible",blur:"hidden",focusout:"hidden",pagehide:"hidden"};a=a||window.event;a.type in b?document.body.className=b[a.type]:(document.body.className=this[e]?"hidden":"visible","hidden"===document.body.className?s_oMain.stopUpdate():s_oMain.startUpdate())}var e="hidden";e in document?document.addEventListener("visibilitychange",a):(e="mozHidden")in document?document.addEventListener("mozvisibilitychange",a):(e="webkitHidden")in
document?document.addEventListener("webkitvisibilitychange",a):(e="msHidden")in document?document.addEventListener("msvisibilitychange",a):"onfocusin"in document?document.onfocusin=document.onfocusout=a:window.onpageshow=window.onpagehide=window.onfocus=window.onblur=a})();function ctlArcadeResume(){null!==s_oMain&&s_oMain.startUpdate()}function ctlArcadePause(){null!==s_oMain&&s_oMain.stopUpdate()}
function getParamValue(a){for(var e=window.location.search.substring(1).split("&"),b=0;b<e.length;b++){var c=e[b].split("=");if(c[0]==a)return c[1]}}
function CSpriteLibrary(){var a,e,b,c,f,d;this.init=function(h,l,g){b=e=0;c=h;f=l;d=g;a={}};this.addSprite=function(b,d){a.hasOwnProperty(b)||(a[b]={szPath:d,oSprite:new Image},e++)};this.getSprite=function(b){return a.hasOwnProperty(b)?a[b].oSprite:null};this._onSpritesLoaded=function(){f.call(d)};this._onSpriteLoaded=function(){c.call(d);++b==e&&this._onSpritesLoaded()};this.loadSprites=function(){for(var b in a)a[b].oSprite.oSpriteLibrary=this,a[b].oSprite.onload=function(){this.oSpriteLibrary._onSpriteLoaded()},
a[b].oSprite.src=a[b].szPath};this.getNumSprites=function(){return e}}var CANVAS_WIDTH=1920,CANVAS_HEIGHT=1080,EDGEBOARD_X=250,EDGEBOARD_Y=80,FPS_TIME=1E3/24,DISABLE_SOUND_MOBILE=!1,PRIMARY_FONT="Lora",SECONDARY_FONT="Arial",STATE_LOADING=0,STATE_MENU=1,STATE_HELP=1,STATE_GAME=3,ON_MOUSE_DOWN=0,ON_MOUSE_UP=1,ON_MOUSE_OVER=2,ON_MOUSE_OUT=3,ON_DRAG_START=4,ON_DRAG_END=5,NUM_DIFFERENT_BALLS=5,ANIMATION_SPEED,WIN_OCCURRENCE=[],PAYOUTS=[],BANK,START_CREDIT=0,BET=[];BET=[.1,.2,.3,.5,1,2,3,5];
var START_BET=50;TEXT_GAMEOVER="YOU LOST YOUR CREDITS";TEXT_CURRENCY="";TEXT_MIN="-";TEXT_PLUS="+";TEXT_PLAY1="PLAY ONE";TEXT_PLAY5="PLAY FIVE";TEXT_UNDO="UNDO";TEXT_CLEAR="CLEAR";TEXT_PAYOUTS="PAYOUTS";TEXT_HITS="HITS";TEXT_PAYS="PAYS";TEXT_CONGRATULATIONS="Congratulations!";TEXT_SHARE_1="You collected <strong>";TEXT_SHARE_2=" points</strong>!<br><br>Share your score with your friends!";TEXT_SHARE_3="My score is ";TEXT_SHARE_4=" points! Can you do better?";
function CPreloader(){var a,e,b,c,f,d,h;this._init=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("progress_bar","./sprites/progress_bar.png");s_oSpriteLibrary.loadSprites();h=new createjs.Container;s_oStage.addChild(h)};this.unload=function(){h.removeAllChildren()};this.hide=function(){var a=this;setTimeout(function(){createjs.Tween.get(d).to({alpha:1},500).call(function(){a.unload();
s_oMain.gotoMenu()})},1E3)};this._onImagesLoaded=function(){};this._onAllImagesLoaded=function(){this.attachSprites();s_oMain.preloaderReady()};this.attachSprites=function(){var l=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));h.addChild(l);l=s_oSpriteLibrary.getSprite("progress_bar");c=createBitmap(l);c.x=CANVAS_WIDTH/2-l.width/2;c.y=CANVAS_HEIGHT-170;h.addChild(c);a=l.width;e=l.height;f=new createjs.Shape;f.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(c.x,c.y,1,e);h.addChild(f);c.mask=
f;b=new createjs.Text("","30px "+PRIMARY_FONT,"#fff");b.x=CANVAS_WIDTH/2;b.y=CANVAS_HEIGHT-125;b.shadow=new createjs.Shadow("#000",2,2,2);b.textBaseline="alphabetic";b.textAlign="center";h.addChild(b);d=new createjs.Shape;d.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);d.alpha=0;h.addChild(d)};this.refreshLoader=function(d){b.text=d+"%";f.graphics.clear();d=Math.floor(d*a/100);f.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(c.x,c.y,d,e)};this._init()}
function CMain(a){var e,b=0,c=0,f=STATE_LOADING,d,h;this.initContainer=function(){s_oCanvas=document.getElementById("canvas");s_oStage=new createjs.Stage(s_oCanvas);createjs.Touch.enable(s_oStage);s_bMobile=jQuery.browser.mobile;!1===s_bMobile&&(s_oStage.enableMouseOver(20),$("body").on("contextmenu","#canvas",function(a){return!1}));s_iPrevTime=(new Date).getTime();createjs.Ticker.addEventListener("tick",this._update);createjs.Ticker.setFPS(30);navigator.userAgent.match(/Windows Phone/i)&&(DISABLE_SOUND_MOBILE=
!0);s_oSpriteLibrary=new CSpriteLibrary;d=new CPreloader};this.preloaderReady=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||this._initSounds();this._loadImages();e=!0};this.soundLoaded=function(){b++;d.refreshLoader(Math.floor(b/c*100));b===c&&this._onRemovePreloader()};this._onRemovePreloader=function(){d.unload();isIOS()||!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||(s_oSoundTrack=createjs.Sound.play("soundtrack",{loop:-1}));this.gotoMenu()};this._initSounds=function(){createjs.Sound.initializeDefaultPlugins()&&
(0<navigator.userAgent.indexOf("Opera")||0<navigator.userAgent.indexOf("OPR")?(createjs.Sound.alternateExtensions=["mp3"],createjs.Sound.addEventListener("fileload",createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/soundtrack.ogg","soundtrack"),createjs.Sound.registerSound("./sounds/click.ogg","click"),createjs.Sound.registerSound("./sounds/game_over.ogg","game_over"),createjs.Sound.registerSound("./sounds/launch_ball.ogg","launch_ball"),createjs.Sound.registerSound("./sounds/win.ogg",
"win")):(createjs.Sound.alternateExtensions=["ogg"],createjs.Sound.addEventListener("fileload",createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/soundtrack.mp3","soundtrack"),createjs.Sound.registerSound("./sounds/click.mp3","click"),createjs.Sound.registerSound("./sounds/game_over.mp3","game_over"),createjs.Sound.registerSound("./sounds/launch_ball.mp3","launch_ball"),createjs.Sound.registerSound("./sounds/win.mp3","win")),c+=5)};this._loadImages=function(){s_oSpriteLibrary.init(this._onImagesLoaded,
this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("but_play","./sprites/but_play.png");s_oSpriteLibrary.addSprite("msg_box","./sprites/msg_box.png");s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("bg_game","./sprites/bg_game.jpg");s_oSpriteLibrary.addSprite("but_exit","./sprites/but_exit.png");s_oSpriteLibrary.addSprite("but_info","./sprites/but_info.png");s_oSpriteLibrary.addSprite("audio_icon","./sprites/audio_icon.png");s_oSpriteLibrary.addSprite("but_plus",
"./sprites/but_plus.png");s_oSpriteLibrary.addSprite("but_generic","./sprites/but_generic.png");s_oSpriteLibrary.addSprite("plus_display","./sprites/plus_display.png");s_oSpriteLibrary.addSprite("num_button","./sprites/num_button.png");s_oSpriteLibrary.addSprite("money_panel","./sprites/money_panel.png");s_oSpriteLibrary.addSprite("payouts","./sprites/payouts.png");s_oSpriteLibrary.addSprite("win_panel","./sprites/win_panel.png");s_oSpriteLibrary.addSprite("hole","./sprites/hole.png");s_oSpriteLibrary.addSprite("tube",
"./sprites/tube.png");s_oSpriteLibrary.addSprite("ball","./sprites/ball.png");s_oSpriteLibrary.addSprite("number","./sprites/number.png");s_oSpriteLibrary.addSprite("but_fullscreen","./sprites/but_fullscreen.png");c+=s_oSpriteLibrary.getNumSprites();s_oSpriteLibrary.loadSprites()};this._onImagesLoaded=function(){b++;d.refreshLoader(Math.floor(b/c*100));b===c&&this._onRemovePreloader()};this._onAllImagesLoaded=function(){};this.onAllPreloaderImagesLoaded=function(){this._loadImages()};this.gotoMenu=
function(){this.gotoGame()};this.gotoGame=function(){h=new CGame(l);f=STATE_GAME;$(s_oMain).trigger("game_start")};this.gotoHelp=function(){new CHelp;f=STATE_HELP};this.stopUpdate=function(){e=!1;createjs.Ticker.paused=!0;$("#block_game").css("display","block");createjs.Sound.setMute(!0)};this.startUpdate=function(){s_iPrevTime=(new Date).getTime();e=!0;createjs.Ticker.paused=!1;$("#block_game").css("display","none");s_bAudioActive&&createjs.Sound.setMute(!1)};this._update=function(a){if(!1!==e){var b=
(new Date).getTime();s_iTimeElaps=b-s_iPrevTime;s_iCntTime+=s_iTimeElaps;s_iCntFps++;s_iPrevTime=b;1E3<=s_iCntTime&&(s_iCurFps=s_iCntFps,s_iCntTime-=1E3,s_iCntFps=0);f===STATE_GAME&&h.update();s_oStage.update(a)}};s_oMain=this;var l=a;ENABLE_CHECK_ORIENTATION=a.check_orientation;ENABLE_FULLSCREEN=a.fullscreen;this.initContainer()}
var s_bMobile,s_bAudioActive=!0,s_iCntTime=0,s_iTimeElaps=0,s_iPrevTime=0,s_iCntFps=0,s_iCurFps=0,s_oDrawLayer,s_oStage,s_oMain,s_oSpriteLibrary,s_oSoundTrack=null,s_oCanvas,s_bFullscreen=!1;
function CTextButton(a,e,b,c,f,d,h){var l,g,m,n,k,p,u;this._init=function(a,b,d,c,e,f,h){l=!1;g=1;m=[];n=[];var x=createBitmap(d),q=Math.ceil(h/20);u=new createjs.Text(c,"bold "+h+"px "+e,"#000000");u.textAlign="center";u.textBaseline="alphabetic";var y=u.getBounds();u.x=d.width/2+q;u.y=Math.floor(d.height/2)+y.height/3+q;p=new createjs.Text(c,"bold "+h+"px "+e,f);p.textAlign="center";p.textBaseline="alphabetic";y=p.getBounds();p.x=d.width/2;p.y=Math.floor(d.height/2)+y.height/3;k=new createjs.Container;
k.x=a;k.y=b;k.regX=d.width/2;k.regY=d.height/2;k.cursor="pointer";k.addChild(x,u,p);s_oStage.addChild(k);this._initListener()};this.unload=function(){k.off("mousedown");k.off("pressup");s_oStage.removeChild(k)};this.setVisible=function(a){k.visible=a};this._initListener=function(){oParent=this;k.on("mousedown",this.buttonDown);k.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,d){m[a]=b;n[a]=d};this.buttonRelease=function(){l||(k.scaleX=1*g,k.scaleY=1*g,m[ON_MOUSE_UP]&&m[ON_MOUSE_UP].call(n[ON_MOUSE_UP]))};
this.buttonDown=function(){l||(k.scaleX=.9*g,k.scaleY=.9*g,m[ON_MOUSE_DOWN]&&m[ON_MOUSE_DOWN].call(n[ON_MOUSE_DOWN]))};this.setTextPosition=function(a){p.y=a;u.y=a+2};this.setText=function(a){p.text=a;u.text=a};this.setPosition=function(a,b){k.x=a;k.y=b};this.setX=function(a){k.x=a};this.setY=function(a){k.y=a};this.getButtonImage=function(){return k};this.getX=function(){return k.x};this.getY=function(){return k.y};this.block=function(a){l=a};this.setScale=function(a){g=a;k.scaleX=a;k.scaleY=a};
this._init(a,e,b,c,f,d,h);return this}
function CTextToggle(a,e,b,c,f,d,h,l,g){var m=1,n,k=!1,p,u,q,t,v,w;this._init=function(a,b,d,c,e,f,m,h,k){n=!1;p=[];u=[];w=createBitmap(d);var x=Math.ceil(m/20);v=new createjs.Text(c," "+m+"px "+e,"#000000");v.textAlign="center";v.textBaseline="alphabetic";var g=v.getBounds();v.x=d.width/2+x;v.y=Math.floor(d.height/2)+g.height/3+x-7;t=new createjs.Text(c," "+m+"px "+e,f);t.textAlign="center";t.textBaseline="alphabetic";g=t.getBounds();t.x=d.width/2;t.y=Math.floor(d.height/2)+g.height/3-7;q=new createjs.Container;
q.x=a;q.y=b;q.regX=d.width/2;q.regY=d.height/2;q.cursor="pointer";h||(a=new createjs.SpriteSheet({images:[d],frames:{width:d.width/2,height:d.height,regX:d.width/2/2,regY:d.height/2},animations:{state_true:[0],state_false:[1]}}),w=createSprite(a,"state_false",d.width/2/2,d.height/2,d.width/2,d.height),v.x=x,v.y=x+17,t.x=0,t.y=17,q.regX=0,q.regY=0);q.addChild(w,v,t);k.addChild(q);this._initListener()};this.unload=function(){q.off("mousedown");q.off("pressup");g.removeChild(q)};this.setVisible=function(a){q.visible=
a};this._initListener=function(){oParent=this;q.on("mousedown",this.buttonDown);q.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,d){p[a]=b;u[a]=d};this.buttonRelease=function(){n||k||(q.scaleX=1*m,q.scaleY=1*m,p[ON_MOUSE_UP]&&p[ON_MOUSE_UP].call(u[ON_MOUSE_UP]))};this.buttonDown=function(){n||k||(q.scaleX=.9*m,q.scaleY=.9*m,p[ON_MOUSE_DOWN]&&p[ON_MOUSE_DOWN].call(u[ON_MOUSE_DOWN]))};this.enable=function(){n=!1;l||w.gotoAndStop("state_true")};this.disable=function(){n=!0;l||w.gotoAndStop("state_false")};
this.setTextPosition=function(a,b){var d=Math.ceil(h/20);v.x=a+d;v.y=b+d;t.x=a;t.y=b};this.setText=function(a){t.text=a;v.text=a};this.setPosition=function(a,b){q.x=a;q.y=b};this.setX=function(a){q.x=a};this.setY=function(a){q.y=a};this.getButtonImage=function(){return q};this.getX=function(){return q.x};this.getY=function(){return q.y};this.block=function(a){k=a};this.setScale=function(a){m=a;q.scaleX=a;q.scaleY=a};this.setScaleX=function(a){w.scaleX=a};this._init(a,e,b,c,f,d,h,l,g);return this}
function CToggle(a,e,b,c){var f,d,h,l;this._init=function(a,b,c,e){d=[];h=[];var m=new createjs.SpriteSheet({images:[c],frames:{width:c.width/2,height:c.height,regX:c.width/2/2,regY:c.height/2},animations:{state_true:[0],state_false:[1]}});f=e;l=createSprite(m,"state_"+f,c.width/2/2,c.height/2,c.width/2,c.height);l.x=a;l.y=b;l.stop();l.cursor="pointer";s_oStage.addChild(l);this._initListener()};this.unload=function(){l.off("mousedown",this.buttonDown);l.off("pressup",this.buttonRelease);s_oStage.removeChild(l)};
this._initListener=function(){l.on("mousedown",this.buttonDown);l.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,c){d[a]=b;h[a]=c};this.setActive=function(a){f=a;l.gotoAndStop("state_"+f)};this.buttonRelease=function(){l.scaleX=1;l.scaleY=1;!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("click");f=!f;l.gotoAndStop("state_"+f);d[ON_MOUSE_UP]&&d[ON_MOUSE_UP].call(h[ON_MOUSE_UP],f)};this.buttonDown=function(){l.scaleX=.9;l.scaleY=.9;d[ON_MOUSE_DOWN]&&d[ON_MOUSE_DOWN].call(h[ON_MOUSE_DOWN])};
this.setPosition=function(a,b){l.x=a;l.y=b};this._init(a,e,b,c)}
function CNumToggle(a,e,b,c){var f,d,h,l,g,m,n,k=[];this._init=function(a,b,c,e){d=!1;h=[];l=[];g=new createjs.Container;g.x=a;g.y=b;g.cursor="pointer";e.addChild(g);a=s_oSpriteLibrary.getSprite("num_button");b={images:[a],framerate:5,frames:{width:a.width/2,height:a.height,regX:a.width/2/2,regY:a.height/2},animations:{state_true:[0],state_false:[1]}};b=new createjs.SpriteSheet(b);f=!1;m=createSprite(b,"state_"+f,a.width/2/2,a.height/2,a.width/2,a.height);m.stop();a=s_oSpriteLibrary.getSprite("ball");
b={images:[a],frames:{width:a.width/NUM_DIFFERENT_BALLS,height:a.height,regX:a.width/NUM_DIFFERENT_BALLS/2,regY:a.height/2},animations:{red:[0],green:[1],cyan:[0],violet:[1],blue:[1]}};b=new createjs.SpriteSheet(b);n=createSprite(b,"red",a.width/NUM_DIFFERENT_BALLS/2,a.height/2,a.width/NUM_DIFFERENT_BALLS,a.height);n.gotoAndStop(0);n.visible=!1;g.addChild(m,n);this._initListener()};this.unload=function(){g.off("mousedown",this.buttonDown);g.off("pressup",this.buttonRelease);c.removeChild(g)};this._initListener=
function(){g.on("mousedown",this.buttonDown);g.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,d){h[a]=b;l[a]=d};this.addEventListenerWithParams=function(a,b,d,c){h[a]=b;l[a]=d;k=c};this.setActive=function(a){f=a;m.gotoAndStop("state_"+f)};this.buttonRelease=function(){d||(!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("click"),f=!f,m.gotoAndStop("state_"+f),h[ON_MOUSE_UP]&&h[ON_MOUSE_UP].call(l[ON_MOUSE_UP],k))};this.buttonDown=function(){d||h[ON_MOUSE_DOWN]&&
h[ON_MOUSE_DOWN].call(l[ON_MOUSE_DOWN],k)};this.setPosition=function(a,b){g.x=a;g.y=b};this.getGlobalPosition=function(){return{x:g.localToGlobal(0,0).x,y:g.localToGlobal(0,0).y}};this.block=function(a){d=a};this.setExtracted=function(a,b){n.visible=a;n.gotoAndStop(b)};this.highlight=function(){m.gotoAndPlay(0)};this.stopHighlight=function(){m.gotoAndStop(1)};this._init(a,e,b,c)}
function CGfxButton(a,e,b){var c,f,d;this._init=function(a,b,e){c=[];f=[];d=createBitmap(e);d.x=a;d.y=b;d.regX=e.width/2;d.regY=e.height/2;d.cursor="pointer";s_oStage.addChild(d);this._initListener()};this.unload=function(){d.off("mousedown",this.buttonDown);d.off("pressup",this.buttonRelease);s_oStage.removeChild(d)};this.setVisible=function(a){d.visible=a};this._initListener=function(){d.on("mousedown",this.buttonDown);d.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,d){c[a]=
b;f[a]=d};this.buttonRelease=function(){d.scaleX=1;d.scaleY=1;c[ON_MOUSE_UP]&&c[ON_MOUSE_UP].call(f[ON_MOUSE_UP])};this.buttonDown=function(){d.scaleX=.9;d.scaleY=.9;c[ON_MOUSE_DOWN]&&c[ON_MOUSE_DOWN].call(f[ON_MOUSE_DOWN])};this.setPosition=function(a,b){d.x=a;d.y=b};this.setX=function(a){d.x=a};this.setY=function(a){d.y=a};this.getButtonImage=function(){return d};this.getX=function(){return d.x};this.getY=function(){return d.y};this._init(a,e,b);return this}
function CMenu(){var a,e,b,c,f,d,h,l,g,m=null,n=null;this._init=function(){f=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));s_oStage.addChild(f);var k=s_oSpriteLibrary.getSprite("but_play");d=new CGfxButton(CANVAS_WIDTH/2,CANVAS_HEIGHT-200,k);d.addEventListener(ON_MOUSE_UP,this._onButPlayRelease,this);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)k=s_oSpriteLibrary.getSprite("audio_icon"),b=CANVAS_WIDTH-k.height/2-10,c=k.height/2+10,l=new CToggle(b,c,k,s_bAudioActive),l.addEventListener(ON_MOUSE_UP,
this._onAudioToggle,this);k=window.document;var p=k.documentElement;m=p.requestFullscreen||p.mozRequestFullScreen||p.webkitRequestFullScreen||p.msRequestFullscreen;n=k.exitFullscreen||k.mozCancelFullScreen||k.webkitExitFullscreen||k.msExitFullscreen;!1===ENABLE_FULLSCREEN&&(m=!1);m&&!1===inIframe()&&(k=s_oSpriteLibrary.getSprite("but_fullscreen"),a=k.width/4+10,e=k.height/2+10,g=new CToggle(a,e,k,s_bFullscreen,!0),g.addEventListener(ON_MOUSE_UP,this._onFullscreenRelease,this));h=new createjs.Shape;
h.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(h);createjs.Tween.get(h).to({alpha:0},1E3).call(function(){h.visible=!1});this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.unload=function(){d.unload();d=null;h.visible=!1;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)l.unload(),l=null;m&&!1===inIframe()&&g.unload();s_oStage.removeChild(f);s_oMenu=f=null};this.refreshButtonPos=function(d,f){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||l.setPosition(b-d,f+c);m&&
!1===inIframe()&&g.setPosition(a+d,e+f)};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onButPlayRelease=function(){this.unload();if(isIOS()&&null===s_oSoundTrack){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)s_oSoundTrack=createjs.Sound.play("soundtrack",{loop:-1})}else!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("click");$(s_oMain).trigger("start_session");s_oMain.gotoGame()};this._onFullscreenRelease=function(){s_bFullscreen?
(n.call(window.document),s_bFullscreen=!1):(m.call(window.document.documentElement),s_bFullscreen=!0);sizeHandler()};s_oMenu=this;this._init()}var s_oMenu=null;
function CGame(a){var e,b,c,f,d,h,l,g,m,n,k,p,u=null,q,t,v,w;this._init=function(){b=BANK;f=START_CREDIT;c=START_BET;d=0;l=1;n=[];var a=createBitmap(s_oSpriteLibrary.getSprite("bg_game"));s_oStage.addChild(a);p=new CInterface;p.refreshBet(c);q=new createjs.Container;q.x=CANVAS_WIDTH/2;q.y=CANVAS_HEIGHT/2;s_oStage.addChild(q);this._initCells();t=new CPayouts(1360,203);a=s_oSpriteLibrary.getSprite("hole");var e=createBitmap(a);e.regX=a.width/2;e.regY=a.height/2;e.x=365;e.y=750;s_oStage.addChild(e);
v=new CAnimBalls(365,260);a=s_oSpriteLibrary.getSprite("tube");a=createBitmap(a);a.x=315;a.y=205;s_oStage.addChild(a);a=(new createjs.Graphics).beginFill("rgba(158,158,158,0.01)").drawRect(0,200,CANVAS_WIDTH,CANVAS_HEIGHT-200);w=new createjs.Shape(a);w.on("click",function(){});w.visible=!1;s_oStage.addChild(w);p.refreshMoney(f.toFixed(2))};this._initCells=function(){var a=s_oSpriteLibrary.getSprite("num_button"),b=a.width/2-5;a=a.height-5;var d=-(10*b)/2+b/2-40,c=-(8*a)/2+a/2+10;g=[];m=[];for(var e=
0,f=0;80>f;f++)g[f]=new CNumToggle(d+f%10*b,c+a*e,f+1,q),g[f].addEventListenerWithParams(ON_MOUSE_UP,this._onButNumRelease,this,f),9===f%10&&e++,m[f]=!1;a=s_oSpriteLibrary.getSprite("number");b=createBitmap(a);b.regX=a.width/2;b.regY=a.height/2;b.x=CANVAS_WIDTH/2-35;b.y=CANVAS_HEIGHT/2+10;s_oStage.addChild(b)};this._onButNumRelease=function(a){this._clearAllSelected();if(m[a]){d--;m[a]=!1;for(var b=0;b<n.length;b++)n[b]===a&&n.splice(b,1)}else d++,m[a]=!0,n.push(a);for(b=0;b<n.length;b++)g[n[b]].setActive(!0);
this._checkActiveButton();t.updatePayouts(d-1);if(9<d)for(b=0;b<m.length;b++)m[b]||g[b].block(!0);else for(b=0;b<m.length;b++)g[b].block(!1)};this._checkActiveButton=function(){2>d?(p.enablePlay1(!1),p.enablePlay5(!1)):(p.enablePlay1(!0),5*c>f?p.enablePlay5(!1):p.enablePlay5(!0))};this.clearSelection=function(){n=[];this._clearAllExtracted();d=0;t.updatePayouts(d);for(var a=0;a<m.length;a++)m[a]=!1,g[a].block(!1),g[a].setActive(!1);this._checkActiveButton()};this.undoSelection=function(){this._clearAllExtracted();
if(0!==d){var a=n.pop();d--;m[a]=!1;g[a].setActive(!1);for(a=0;a<m.length;a++)g[a].block(!1);this._checkActiveButton();t.updatePayouts(d)}};this.selectBet=function(a){this._clearAllExtracted();"add"===a?c+=5:c-=5;c>game_MaxBet_newTRX?c=game_MaxBet_newTRX:0>c&&(c=0);c>f&&(c=Math.floor(f));p.refreshBet(c);this._checkActiveButton()};this.play5=function(){l=5;this.play()};this.updateCredit=function(a,b){f=a;b&&p.refreshMoney(f.toFixed(2))};this.play=function(){if(!(2>d||10<d||window.wallet_requesting)){window.wallet_requesting=
!0;for(var a=[],b=0;b<n.length;b++)a[b]=n[b]+1;userBetSend(a,c,this.serverReturns)}};this.serverReturns=function(a,b){window.wallet_requesting&&(window.wallet_requesting=!1,"object"==typeof a&&this.play2(!0,a,b))};this.play2=function(a,e,m){this._clearAllExtracted();this.smartBlockGUI(!1);p.refreshMoney(f.toFixed(2));if(a)k=e,h=m,this._animExtraction();else{a=null;for(e=0;e<PAYOUTS[d-1].pays.length;e++)if(PAYOUTS[d-1].pays[e]*c<=b){a=e;break}null===a?this._extractLosingCombination():this._checkWin(a)}};
this._checkWin=function(a){var b=100*Math.random();trace("iRandWin: "+b);b<WIN_OCCURRENCE[d-1]?this._extractWinCombination(a):this._extractLosingCombination()};this._extractWinCombination=function(a){e=!0;for(var b=[],c=PAYOUTS[d-1].pays.length-1;c>=a;c--)for(var f=0;f<PAYOUTS[d-1].occurrence[c];f++)b.push(PAYOUTS[d-1].hits[c]);a=Math.floor(Math.random()*b.length);f=[];for(c=0;c<n.length;c++)f[c]=n[c]+1;shuffle(f);var l=[];for(c=0;c<m.length;c++)m[c]||l.push(c+1);shuffle(l);k=[];for(c=0;20>c;c++)c<
b[a]?k.push(f[c]):k.push(l[c]);shuffle(k);for(c=0;20>c;c++);h=b[a];this._animExtraction()};this._extractLosingCombination=function(){e=!1;for(var a=Math.round(Math.random()*(PAYOUTS[d-1].hits[PAYOUTS[d-1].hits.length-1]-1)),b=[],c=0;c<n.length;c++)b[c]=n[c]+1;shuffle(b);var f=[];for(c=0;c<m.length;c++)m[c]||f.push(c+1);shuffle(f);k=[];for(c=0;20>c;c++)c<a?k.push(b[c]):k.push(f[c]);shuffle(k);h=0;this._animExtraction()};this._animExtraction=function(){for(var a=[],b=0;b<k.length;b++)a.push(g[k[b]-
1].getGlobalPosition());v.startAnimation(a)};this._checkContinueGame=function(){for(var a=0;a<PAYOUTS[d-1].hits.length;a++)if(PAYOUTS[d-1].hits[a]===h){a=c*PAYOUTS[d-1].pays[a];a=parseFloat(a.toFixed(1));t.showWin(a);t.highlightWin(h);break}p.refreshMoney(f.toFixed(2));e&&(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)&&createjs.Sound.play("win");v.resetBalls();this.highlightCell();$(s_oMain).trigger("save_score",f);c>f&&(c=Math.floor(f),p.refreshBet(c));c>game_MaxBet_newTRX&&(c=game_MaxBet_newTRX,p.refreshBet(c));
1===l?this.smartBlockGUI(!0):(l--,setTimeout(function(){r.play()},2E3))};this.showExtracted=function(a,b){g[k[a]-1].setExtracted(!0,b)};this._clearAllExtracted=function(){t.showWin(0);t.stopHighlight();for(var a=0;a<m.length;a++)g[a].setExtracted(!1,0);for(a=0;a<n.length;a++)g[n[a]].setActive(!0)};this._clearAllSelected=function(){t.showWin(0);t.stopHighlight();for(var a=0;a<m.length;a++)g[a].setExtracted(!1,0)};this.smartBlockGUI=function(a){a?(w.visible=!1,p.enableAllButton(!0),5*c<=f?p.enablePlay5(!0):
p.enablePlay5(!1)):(w.visible=!0,p.enableAllButton(!1))};this.getCurMoney=function(){return f};this.restartGame=function(){this.unload();this._init()};this.unload=function(){p.unload();null!==u&&u.unload();createjs.Tween.removeAllTweens();s_oStage.removeAllChildren()};this.onExit=function(){$("#contractModal").modal("show")};this._onExitHelp=function(){_bStartGame=!0};this.gameOver=function(){u=CEndPanel(s_oSpriteLibrary.getSprite("msg_box"));u.show()};this.highlightCell=function(){for(var a=0;a<
k.length;a++)for(var b=0;b<n.length;b++)k[a]===n[b]+1&&g[n[b]].highlight()};this.update=function(){};s_oGame=this;WIN_OCCURRENCE=a.win_occurrence;PAYOUTS=a.payouts;BANK=a.bank_money;ANIMATION_SPEED=a.animation_speed;var r=this;this._init()}var s_oGame;
function CInterface(){var a,e,b,c,f,d,h,l,g,m,n,k,p,u,q,t,v=null,w=null;this._init=function(){var r=s_oSpriteLibrary.getSprite("but_info");f=CANVAS_WIDTH-r.height/2-20;d=r.height/2+10;l=new CGfxButton(f,d,r,!0);l.addEventListener(ON_MOUSE_UP,this._onExit,this);b=CANVAS_WIDTH-r.width/2-100-15;c=r.height/2+10;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)r=s_oSpriteLibrary.getSprite("audio_icon"),h=new CToggle(b,c,r,s_bAudioActive),h.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);r=window.document;
var x=r.documentElement;v=x.requestFullscreen||x.mozRequestFullScreen||x.webkitRequestFullScreen||x.msRequestFullscreen;w=r.exitFullscreen||r.mozCancelFullScreen||r.webkitExitFullscreen||r.msExitFullscreen;!1===ENABLE_FULLSCREEN&&(v=!1);v&&!1===inIframe()&&(r=s_oSpriteLibrary.getSprite("but_fullscreen"),a=r.width/4+10,e=r.height/2+10,t=new CToggle(a,e,r,s_bFullscreen,!0),t.addEventListener(ON_MOUSE_UP,this._onFullscreenRelease,this));r=s_oSpriteLibrary.getSprite("money_panel");n=new CTextButton(560,
65,r,"0",PRIMARY_FONT,"#ffffff",40);n.block(!0);r=s_oSpriteLibrary.getSprite("plus_display");k=new CTextButton(480,CANVAS_HEIGHT-130,r,"$1",PRIMARY_FONT,"#ffffff",40,!1,s_oStage);k.setTextPosition(51);k.block(!0);r=s_oSpriteLibrary.getSprite("but_plus");m=new CTextToggle(638,CANVAS_HEIGHT-130,r,TEXT_PLUS,PRIMARY_FONT,"#ffffff",70,!1,s_oStage);m.enable();m.setTextPosition(0,20);m.addEventListener(ON_MOUSE_UP,this._onButPlusRelease,this);r=s_oSpriteLibrary.getSprite("but_plus");g=new CTextToggle(320,
CANVAS_HEIGHT-130,r,TEXT_MIN,PRIMARY_FONT,"#ffffff",70,!1,s_oStage);g.enable();g.setTextPosition(0,20);g.setScaleX(-1);g.addEventListener(ON_MOUSE_UP,this._onButMinRelease,this);r=s_oSpriteLibrary.getSprite("but_generic");p=new CTextToggle(940,CANVAS_HEIGHT-130,r,TEXT_PLAY1,PRIMARY_FONT,"#ffffff",30,!1,s_oStage);p.disable();p.setTextPosition(0,10);p.addEventListener(ON_MOUSE_UP,this._onPlay1,this);r=s_oSpriteLibrary.getSprite("but_generic");u=new CTextToggle(1300,CANVAS_HEIGHT-130,r,TEXT_UNDO,PRIMARY_FONT,
"#ffffff",30,!1,s_oStage);u.enable();u.setTextPosition(0,10);u.addEventListener(ON_MOUSE_UP,this._onUndo,this);r=s_oSpriteLibrary.getSprite("but_generic");q=new CTextToggle(1540,CANVAS_HEIGHT-130,r,TEXT_CLEAR,PRIMARY_FONT,"#ffffff",30,!1,s_oStage);q.enable();q.setTextPosition(0,10);q.addEventListener(ON_MOUSE_UP,this._onClear,this);this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.unload=function(){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)h.unload(),h=null;l.unload();n.unload();k.unload();g.unload();
m.unload();p.unload();u.unload();q.unload();v&&!1===inIframe()&&t.unload();s_oInterface=null};this.refreshButtonPos=function(m,k){l.setPosition(f-m,k+d);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||h.setPosition(b-m,k+c);v&&!1===inIframe()&&t.setPosition(a+m,e+k)};this.refreshBet=function(a){k.setText(TEXT_CURRENCY+a)};this.refreshMoney=function(a){n.setText(TEXT_CURRENCY+a)};this.enablePlus=function(a){a?m.enable():m.disable()};this.enableMin=function(a){a?g.enable():g.disable()};this.enablePlay1=
function(a){a?p.enable():p.disable()};this.enablePlay5=function(a){};this.enableUndo=function(a){a?u.enable():u.disable()};this.enableClear=function(a){a?q.enable():q.disable()};this.enableAllButton=function(a){this.enablePlus(a);this.enableMin(a);this.enablePlay1(a);this.enablePlay5(a);this.enableUndo(a);this.enableClear(a)};this._onClear=function(){s_oGame.clearSelection()};this._onUndo=function(){s_oGame.undoSelection()};this._onButPlusRelease=function(){s_oGame.selectBet("add")};this._onButMinRelease=
function(){s_oGame.selectBet("remove")};this._onPlay1=function(){s_oGame.play()};this._onPlay5=function(){s_oGame.play5()};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onFullscreenRelease=function(){s_bFullscreen?(w.call(window.document),s_bFullscreen=!1):(v.call(window.document.documentElement),s_bFullscreen=!0);sizeHandler()};this._onExit=function(){$(s_oMain).trigger("end_session");var a=s_oGame.getCurMoney();$(s_oMain).trigger("share_event",
a);s_oGame.onExit()};s_oInterface=this;this._init();return this}var s_oInterface=null;
function CHelpPanel(){var a,e,b,c,f,d;this._init=function(){var h=this;f=createBitmap(s_oSpriteLibrary.getSprite("msg_box"));var g=CANVAS_WIDTH/2,m=CANVAS_HEIGHT/2-200;e=new createjs.Text(TEXT_HELP1," 24px "+SECONDARY_FONT,"#000000");e.x=g+2;e.y=m+2;e.textAlign="center";e.textBaseline="alphabetic";e.lineWidth=400;a=new createjs.Text(TEXT_HELP1," 24px "+SECONDARY_FONT,"#ffffff");a.x=g;a.y=m;a.textAlign="center";a.textBaseline="alphabetic";a.lineWidth=400;g=CANVAS_WIDTH/2-130;m=CANVAS_HEIGHT/2-40;c=
new createjs.Text(TEXT_HELP2," 24px "+SECONDARY_FONT,"#000000");c.x=g+2;c.y=m+2;c.textAlign="center";c.textBaseline="alphabetic";c.lineWidth=280;b=new createjs.Text(TEXT_HELP2," 24px "+SECONDARY_FONT,"#ffffff");b.x=g;b.y=m;b.textAlign="center";b.textBaseline="alphabetic";b.lineWidth=280;d=new createjs.Container;d.addChild(f,e,a,c,b);d.alpha=0;s_oStage.addChild(d);createjs.Tween.get(d).to({alpha:1},700);d.on("pressup",function(){h._onExitHelp()})};this.unload=function(){s_oStage.removeChild(d);var a=
this;d.off("pressup",function(){a._onExitHelp()})};this._onExitHelp=function(){h.unload();s_oGame._onExitHelp()};var h=this;this._init()}
function CEndPanel(a){var e,b,c,f;this._init=function(a){e=createBitmap(a);e.x=0;e.y=0;c=new createjs.Text("","bold 60px "+PRIMARY_FONT,"#000");c.x=CANVAS_WIDTH/2+2-60;c.y=CANVAS_HEIGHT/2-48;c.textAlign="center";c.textBaseline="middle";c.lineWidth=500;f=new createjs.Text("","bold 60px "+PRIMARY_FONT,"#ffffff");f.x=CANVAS_WIDTH/2-60;f.y=CANVAS_HEIGHT/2-50;f.textAlign="center";f.textBaseline="middle";f.lineWidth=500;b=new createjs.Container;b.alpha=0;b.visible=!1;b.addChild(e,c,f);s_oStage.addChild(b)};
this.unload=function(){b.off("mousedown",this._onExit)};this._initListener=function(){b.on("mousedown",this._onExit)};this.show=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("game_over");c.text=TEXT_GAMEOVER;f.text=TEXT_GAMEOVER;b.visible=!0;var a=this;createjs.Tween.get(b).to({alpha:1},500).call(function(){a._initListener()})};this._onExit=function(){b.off("mousedown",this._onExit);s_oStage.removeChild(b);$(s_oMain).trigger("end_session");s_oGame.onExit()};this._init(a);
return this}
function CPayouts(a,e){var b=0,c,f,d,h,l,g,m,n,k;this._init=function(a,b){f=new createjs.Container;f.x=a;f.y=b;s_oStage.addChild(f);var c=createBitmap(s_oSpriteLibrary.getSprite("payouts")),e=createBitmap(s_oSpriteLibrary.getSprite("win_panel"));e.x=-6;e.y=577;l=new createjs.Text(TEXT_PAYOUTS," 34px "+PRIMARY_FONT,"#ffffff");l.x=150;l.y=40;l.textAlign="center";l.textBaseline="middle";l.lineWidth=400;d=new createjs.Text(TEXT_HITS," 30px "+PRIMARY_FONT,"#ffffff");d.x=80;d.y=130;d.textAlign="center";
d.textBaseline="alphabetic";d.lineWidth=400;h=new createjs.Text(TEXT_PAYS," 30px "+PRIMARY_FONT,"#ffffff");h.x=210;h.y=130;h.textAlign="center";h.textBaseline="alphabetic";h.lineWidth=400;f.addChild(c,d,h,l,e);m=[];n=[];k=[];for(c=0;6>c;c++)m[c]=190+50*c,n[c]=new createjs.Text("-","bold 36px "+PRIMARY_FONT,"#ffffff"),n[c].x=80,n[c].y=m[c],n[c].textAlign="center",n[c].textBaseline="middle",f.addChild(n[c]),k[c]=new createjs.Text("-","bold 36px "+PRIMARY_FONT,"#ffffff"),k[c].x=210,k[c].y=m[c],k[c].textAlign=
"center",k[c].textBaseline="middle",f.addChild(k[c]);g=new createjs.Text(TEXT_CURRENCY+"0","bold 40px "+PRIMARY_FONT,"#ffffff");g.x=150;g.y=646;g.textAlign="center";g.textBaseline="middle";f.addChild(g)};this.unload=function(){s_oStage.removeChild(f)};this.updatePayouts=function(a){if(0>a)var b=0;else{for(b=0;b<PAYOUTS[a].hits.length;b++)n[b].text=PAYOUTS[a].hits[b],k[b].text=PAYOUTS[a].pays[b];b=PAYOUTS[a].hits.length}for(;6>b;b++)n[b].text="-",k[b].text="-"};this.showWin=function(a){g.text=TEXT_CURRENCY+
a};this.highlightWin=function(a){for(var b=0;6>b;b++)if(n[b].text===a){c=b;this._flicker(b);break}};this._flicker=function(a){b=1===b?0:1;createjs.Tween.get(n[a]).to({alpha:b},250,createjs.Ease.cubicOut);createjs.Tween.get(k[a]).to({alpha:b},250,createjs.Ease.cubicOut).call(function(){p._flicker(a)})};this.stopHighlight=function(){n[c]&&(createjs.Tween.removeTweens(n[c]),createjs.Tween.removeTweens(k[c]),n[c].alpha=1,k[c].alpha=1)};var p=this;this._init(a,e)}
function CAnimBalls(a,e){var b,c,f,d,h,l;this._init=function(a,e){b=ANIMATION_SPEED;f=7;var m=s_oSpriteLibrary.getSprite("ball"),h=new createjs.SpriteSheet({images:[m],frames:{width:m.width/NUM_DIFFERENT_BALLS,height:m.height,regX:m.width/NUM_DIFFERENT_BALLS/2,regY:m.height/2},animations:{red:[0],green:[1],cyan:[0],violet:[1],blue:[1]}});d=[];l=[];c=m.height;for(var g=0;28>g;g++){var n=Math.floor(Math.random()*NUM_DIFFERENT_BALLS);d[g]=createSprite(h,n,m.width/NUM_DIFFERENT_BALLS/2,m.height/2,m.width/
NUM_DIFFERENT_BALLS,m.height);d[g].gotoAndStop(n);d[g].x=a;g>f?(d[g].alpha=0,d[g].scaleX=d[g].scaleY=0,d[g].y=e+f*c):(d[g].y=e+g*c,l[g]=e+g*c)}for(g=0;28>g;g++)s_oStage.addChild(d[28-g-1])};this.unload=function(){for(var a=0;26>a;a++)s_oStage.removeChild(d[a])};this.startAnimation=function(a){h=[];for(var b=0;20>b;b++)h[b]=a[b];this._animBalls(0)};this._animBalls=function(a){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("launch_ball");createjs.Tween.get(d[a]).to({y:-200},2*b,createjs.Ease.quartOut).to({y:h[a].y},
3*b,createjs.Ease.bounceOut).call(function(){s_oGame.showExtracted(a,d[a].currentFrame);d[a].visible=!1;19>a||s_oGame._checkContinueGame()});createjs.Tween.get(d[a]).to({x:h[a].x},5*b);for(var c=0,e=a+1;e<a+f+1;e++)createjs.Tween.get(d[e]).to({y:l[c]},b),c++;createjs.Tween.get(d[a+f+1]).to({scaleX:1,scaleY:1,alpha:1},b,createjs.Ease.cubicIn).call(function(){19>a&&g._animBalls(a+1)})};this.resetBalls=function(){for(var b=0;28>b;b++)if(d[b].visible=!0,d[b].x=a,b<=f)d[b].y=e+b*c,d[b].gotoAndStop(d[20+
b].currentFrame);else if(b>f){var g=Math.floor(Math.random()*NUM_DIFFERENT_BALLS);d[b].gotoAndStop(g);d[b].alpha=0;d[b].scaleX=d[b].scaleY=0;d[b].y=e+f*c}else g=Math.floor(Math.random()*NUM_DIFFERENT_BALLS),d[b].gotoAndStop(g),d[b].y=e+b*c};var g=this;this._init(a,e)};